In [1]:
# Unzip the file
import zipfile
import os

with zipfile.ZipFile('sales_data.zip', 'r') as zip_ref:
    zip_ref.extractall('sales_data')

print(" File unzipped successfully!")
print("Files extracted:")
for f in os.listdir('sales_data'):
    print(f"  - {f}")

 File unzipped successfully!
Files extracted:
  - wallets.csv
  - wall-art.csv
  - foundation.csv
  - swim-tops.csv
  - nightdress.csv
  - innerwear-vests.csv
  - handbags.csv
  - dresses.csv
  - dinnerware.csv
  - trolley-bag.csv
  - belts.csv
  - lounge-pants.csv
  - bodysuit.csv
  - shorts.csv
  - night-suits.csv
  - ring.csv
  - duffel-bag.csv
  - bracelet.csv
  - showpieces.csv
  - scarves.csv
  - flats.csv
  - boots.csv
  - camisoles.csv
  - earrings.csv
  - bra.csv
  - runners.csv
  - tunics.csv
  - sports-shoes.csv
  - perfume-and-body-mist.csv
  - briefs.csv
  - lounge-shorts.csv
  - candle-holders.csv
  - kurta-sets.csv
  - tights.csv
  - gloves.csv
  - formal-shoes.csv
  - jumpsuit.csv
  - casual-shoes.csv
  - caps.csv
  - README.md
  - hair-brush-and-comb.csv
  - kurtas.csv
  - hair-cream-and-mask.csv
  - tops.csv
  - bath-towels.csv
  - shirts.csv
  - lounge-tshirts.csv
  - dupatta.csv
  - floor-mats--dhurries.csv
  - bath-robe.csv
  - sarees.csv
  - shaving-essentials.csv
  - backpacks.csv
  - yoga-mats.csv
  - ethnic-dresses.csv
  - watches.csv
  - shampoo-and-conditioner.csv
  - bedsheets.csv
  - jackets.csv
  - flip-flops.csv
  - clothing-set.csv
  - chair-cover.csv
  - face-wash-and-cleanser.csv
  - mangalsutra.csv
  - palazzos.csv
  - tshirts.csv
  - Combined_dataset.csv
  - thermal-bottoms.csv
  - headphones.csv
  - hair-accessory.csv
  - sherwani.csv
  - hair-masks.csv
  - cutlery.csv
  - dungarees.csv
  - lipstick.csv
  - sweaters.csv
  - mobile-accessories.csv
  - outdoor-masks.csv
  - table-covers.csv
  - clutches.csv
  - pillow-covers.csv
  - sunglasses.csv
  - home-fragrance-set.csv
  - boxers.csv
  - co-ords.csv
  - saree-blouse.csv
  - sandals.csv
  - trunk.csv
  - curtains-and-sheers.csv
  - face-moisturisers.csv
  - sweatshirts.csv
  - jeans.csv
  - towel-set.csv
  - kurtis.csv
  - skirts.csv
  - heels.csv
  - bathroom-accessories.csv
  - trousers.csv
  - track-pants.csv

In [2]:
import pandas as pd
import numpy as np

# Load the main combined dataset
df = pd.read_csv('sales_data/Combined_dataset.csv')

print(" Dataset loaded successfully!")
print(f"   Rows    : {df.shape[0]:,}")
print(f"   Columns : {df.shape[1]}")

 Dataset loaded successfully!
   Rows    : 1,000
   Columns : 24

In [3]:
# First and last rows
print("=== First 5 rows ===")
display(df.head())

print("\n=== Last 5 rows ===")
display(df.tail())

=== First 5 rows ===

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

=== Last 5 rows ===

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [4]:
# Shape and column names
print(f"Shape: {df.shape}  →  {df.shape[0]} rows × {df.shape[1]} columns")
print()
print("Column Names:")
for i, col in enumerate(df.columns, 1):
    print(f"  {i:>2}. {col}")

Shape: (1000, 24)  →  1000 rows × 24 columns

Column Names:
   1. product_id
   2. title
   3. product_description
   4. rating
   5. ratings_count
   6. initial_price
   7. discount
   8. final_price
   9. currency
  10. images
  11. delivery_options
  12. product_details
  13. breadcrumbs
  14. product_specifications
  15. amount_of_stars
  16. what_customers_said
  17. seller_name
  18. sizes
  19. videos
  20. seller_information
  21. variations
  22. best_offer
  23. more_offers
  24. category

In [5]:
print("=== Data Types ===")
print(df.dtypes)

=== Data Types ===
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [7]:
display(df.describe())

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [8]:
print("=== Top 15 Product Categories ===")
print(df['category'].value_counts().head(15))
print(f"\nTotal unique categories: {df['category'].nunique()}")

=== Top 15 Product Categories ===
category
tops            122
dresses         100
shirts           97
jeans            57
sports-shoes     51
tshirts          39
earrings         34
sweaters         34
jackets          29
casual-shoes     23
kurta-sets       22
sarees           22
shorts           21
kurtas           20
sweatshirts      20
Name: count, dtype: int64

Total unique categories: 97

In [9]:
print("=== Missing Values BEFORE Cleaning ===")
missing       = df.isnull().sum()
missing_pct   = (missing / len(df) * 100).round(1)
missing_table = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})
display(missing_table[missing_table['Missing Count'] > 0])
print(f"\nTotal missing cells: {df.isnull().sum().sum()}")

=== Missing Values BEFORE Cleaning ===

                     Missing Count  Missing %
discount                       121       12.1
what_customers_said            573       57.3
seller_name                    301       30.1
videos                         781       78.1
seller_information             301       30.1
variations                     562       56.2

Total missing cells: 2639

In [12]:
df['discount']            = df['discount'].fillna(0)
df['what_customers_said'] = df['what_customers_said'].fillna('No reviews')
df['seller_name']         = df['seller_name'].fillna('Unknown Seller')
df['seller_information']  = df['seller_information'].fillna('N/A')
df['variations']          = df['variations'].fillna('No variations')
df['videos']              = df['videos'].fillna('No video')

# Verify
print("=== Missing Values AFTER Cleaning ===")
print(df.isnull().sum())
print(f"\n Total missing cells remaining: {df.isnull().sum().sum()}")

=== Missing Values AFTER Cleaning ===
product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

 Total missing cells remaining: 0

In [13]:
# Filter rows
high_rated = df[df['rating'] >= 4.0]
print(f"High-rated (≥4.0): {len(high_rated)} items")

big_discount = df[df['discount'] > 60]
print(f"Discount > 60%: {len(big_discount)} items")

# Select columns
display(df[['product_id', 'title', 'category', 'rating', 'initial_price', 'discount']].head(5))

# loc and iloc
display(df.loc[0:4, ['title', 'category', 'initial_price']])
display(df.iloc[0:5, 0:4])

High-rated (≥4.0): 615 items
Discount > 60%: 332 items

   product_id           title   category  rating  initial_price  discount
0     8376765     Lino Perros  backpacks     3.8           3995      58.0
1     9136281  Tommy Hilfiger  backpacks     4.5           2899      35.0
2    17633752           Lavie  backpacks     4.4           2999      65.0
3     1376949          F Gear  backpacks     4.4           1675      52.0
4    13939916       MYTRIDENT  bath-robe     4.7           2899      17.0

            title   category  initial_price
0     Lino Perros  backpacks           3995
1  Tommy Hilfiger  backpacks           2899
2           Lavie  backpacks           2999
3          F Gear  backpacks           1675
4       MYTRIDENT  bath-robe           2899

,product_id,title,product_description,rating
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7

In [14]:
print(f"Before: {len(df)} rows | Duplicates: {df.duplicated().sum()}")
df = df.drop_duplicates().reset_index(drop=True)
print(f"After : {len(df)} rows")

Before: 1000 rows | Duplicates: 0
After : 1000 rows

In [15]:
df['quantity']     = 1
df['total_amount'] = df['initial_price'] * df['quantity']

display(df[['title', 'initial_price', 'quantity', 'total_amount']].head(5))

            title  initial_price  quantity  total_amount
0     Lino Perros           3995         1          3995
1  Tommy Hilfiger           2899         1          2899
2           Lavie           2999         1          2999
3          F Gear           1675         1          1675
4       MYTRIDENT           2899         1          2899

In [16]:
df.to_csv('Combined_dataset_cleaned.csv', index=False)
print(f" Saved! Shape: {df.shape}")

from google.colab import files
files.download('Combined_dataset_cleaned.csv')

 Saved! Shape: (1000, 26)

In [17]:
!git config --global user.email "peeyushraj1010@gmail.com"
!git config --global user.name "Peeyush1010"

In [22]:
!ls /content/

Combined_dataset_cleaned.csv  sales_data.zip  week1_project
sales_data		      sample_data